# Generated by Django 4.0.4 on 2022-05-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0002_alter_produits_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='client',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Commandes',
        ),
        migrations.DeleteModel(
            name='Produits',
        ),
    ]
