from .categories import CategoriesDeleteView
from .categories import CategoriesUpdateView
from .categories import CategoriesDetailView
from .categories import CategoriesCreateView
from .categories import CategoriesListView
from .clients import ClientsDeleteView
from .clients import ClientsUpdateView
from .clients import ClientsDetailView
from .clients import ClientsCreateView
from .clients import ClientsListView
from .commandes import CommandesDeleteView
from .commandes import CommandesUpdateView
from .commandes import CommandesDetailView
from .commandes import CommandesCreateView
from .commandes import CommandesListView
from .produit import ProduitDeleteView
from .produit import ProduitUpdateView
from .produit import ProduitDetailView
from .produit import ProduitCreateView
from .produit import ProduitListView
