# Generated by Django 4.0.4 on 2022-05-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='commande',
            field=models.TextField(default='vide'),
            preserve_default=False,
        ),
    ]
