# Generated by Django 4.0.4 on 2022-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_commandes_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
