# Generated by Django 4.0.4 on 2022-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_commandes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='photo',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
