# Generated by Django 4.0.4 on 2022-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_produits_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='commande',
            field=models.TextField(null=True),
        ),
    ]
