# Generated by Django 4.0.4 on 2022-06-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_rename_maraue_produits_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='commande_details',
            field=models.TextField(null=True),
        ),
    ]
