# Generated by Django 4.0.4 on 2022-06-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_commandes_commande_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='commande_details',
        ),
        migrations.AlterField(
            model_name='commandes',
            name='commande',
            field=models.TextField(default='{}'),
        ),
    ]
