# Generated by Django 4.0.4 on 2022-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_commandes_commande_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
