# Generated by Django 4.0.4 on 2022-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_alter_produits_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
