# Generated by Django 4.0.5 on 2022-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_clients_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
