# Generated by Django 4.0.5 on 2022-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_alter_produits_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='photo',
            field=models.FileField(upload_to='produit'),
        ),
    ]
