from .categories_delete_test import CategoriesDeleteTestCase
from .categories_update_test import CategoriesUpdateTestCase
from .categories_detail_test import CategoriesDetailTestCase
from .categories_create_test import CategoriesCreateTestCase
from .categories_list_test import CategoriesListTestCase
