from .test import TestDeleteTestCase
from .test import TestUpdateTestCase
from .test import TestDetailTestCase
from .test import TestCreateTestCase
from .test import TestListTestCase
from .categories import CategoriesDeleteTestCase
from .categories import CategoriesUpdateTestCase
from .categories import CategoriesDetailTestCase
from .categories import CategoriesCreateTestCase
from .categories import CategoriesListTestCase
from .clients import ClientsDeleteTestCase
from .clients import ClientsUpdateTestCase
from .clients import ClientsDetailTestCase
from .clients import ClientsCreateTestCase
from .clients import ClientsListTestCase
from .commandes import CommandesDeleteTestCase
from .commandes import CommandesUpdateTestCase
from .commandes import CommandesDetailTestCase
from .commandes import CommandesCreateTestCase
from .commandes import CommandesListTestCase
from .produit import ProduitDeleteTestCase
from .produit import ProduitUpdateTestCase
from .produit import ProduitDetailTestCase
from .produit import ProduitCreateTestCase
from .produit import ProduitListTestCase
